### ISSUE TITLE
Document API functions for script use

### ISSUE THREAD

**Issue by vadi2** [takilara/cpc#5]
I see a lot of people trying to use `expandAlias("#bid")` or `send("#bid")` because they don't know the API functions to use - if they were available in the README, I reckon that issue would be solved.

**Comment by takilara** [comment]
Thanks, I'll add those to the documentation

**Comment by takilara** [comment]
I've done a quick stab at it, not the cleanest, but should help

**Comment by vadi2** [comment]
Thanks!
